/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Background: typeof import('./src/components/Background.vue')['default']
    Card: typeof import('./src/components/custom/Card.vue')['default']
    Col: typeof import('./src/components/custom/Col.vue')['default']
    Collapse: typeof import('./src/components/custom/Collapse.vue')['default']
    CollapseItem: typeof import('./src/components/custom/CollapseItem.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Hitokoto: typeof import('./src/components/Hitokoto.vue')['default']
    Links: typeof import('./src/components/Links.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Message: typeof import('./src/components/custom/Message.vue')['default']
    MoreContent: typeof import('./src/components/MoreContent.vue')['default']
    Music: typeof import('./src/components/Music.vue')['default']
    Player: typeof import('./src/components/Player.vue')['default']
    Progress: typeof import('./src/components/custom/Progress.vue')['default']
    Radio: typeof import('./src/components/custom/Radio.vue')['default']
    RadioGroup: typeof import('./src/components/custom/RadioGroup.vue')['default']
    Row: typeof import('./src/components/custom/Row.vue')['default']
    Set: typeof import('./src/components/Set.vue')['default']
    Slider: typeof import('./src/components/custom/Slider.vue')['default']
    SocialLinks: typeof import('./src/components/SocialLinks.vue')['default']
    Switch: typeof import('./src/components/custom/Switch.vue')['default']
    TimeCapsule: typeof import('./src/components/TimeCapsule.vue')['default']
    Tooltip: typeof import('./src/components/custom/Tooltip.vue')['default']
    Weather: typeof import('./src/components/Weather.vue')['default']
  }
}

// For TSX support
declare global {
  const Background: typeof import('./src/components/Background.vue')['default']
  const Card: typeof import('./src/components/custom/Card.vue')['default']
  const Col: typeof import('./src/components/custom/Col.vue')['default']
  const Collapse: typeof import('./src/components/custom/Collapse.vue')['default']
  const CollapseItem: typeof import('./src/components/custom/CollapseItem.vue')['default']
  const ElCard: typeof import('element-plus/es')['ElCard']
  const ElCol: typeof import('element-plus/es')['ElCol']
  const ElCollapse: typeof import('element-plus/es')['ElCollapse']
  const ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
  const ElProgress: typeof import('element-plus/es')['ElProgress']
  const ElRadio: typeof import('element-plus/es')['ElRadio']
  const ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
  const ElRow: typeof import('element-plus/es')['ElRow']
  const ElSlider: typeof import('element-plus/es')['ElSlider']
  const ElSwitch: typeof import('element-plus/es')['ElSwitch']
  const ElTooltip: typeof import('element-plus/es')['ElTooltip']
  const Footer: typeof import('./src/components/Footer.vue')['default']
  const Hitokoto: typeof import('./src/components/Hitokoto.vue')['default']
  const Links: typeof import('./src/components/Links.vue')['default']
  const Loading: typeof import('./src/components/Loading.vue')['default']
  const Message: typeof import('./src/components/custom/Message.vue')['default']
  const MoreContent: typeof import('./src/components/MoreContent.vue')['default']
  const Music: typeof import('./src/components/Music.vue')['default']
  const Player: typeof import('./src/components/Player.vue')['default']
  const Progress: typeof import('./src/components/custom/Progress.vue')['default']
  const Radio: typeof import('./src/components/custom/Radio.vue')['default']
  const RadioGroup: typeof import('./src/components/custom/RadioGroup.vue')['default']
  const Row: typeof import('./src/components/custom/Row.vue')['default']
  const Set: typeof import('./src/components/Set.vue')['default']
  const Slider: typeof import('./src/components/custom/Slider.vue')['default']
  const SocialLinks: typeof import('./src/components/SocialLinks.vue')['default']
  const Switch: typeof import('./src/components/custom/Switch.vue')['default']
  const TimeCapsule: typeof import('./src/components/TimeCapsule.vue')['default']
  const Tooltip: typeof import('./src/components/custom/Tooltip.vue')['default']
  const Weather: typeof import('./src/components/Weather.vue')['default']
}