/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Background: typeof import('./src/components/Background.vue')['default']
    Card: typeof import('./src/components/custom/Card.vue')['default']
    Col: typeof import('./src/components/custom/Col.vue')['default']
    Collapse: typeof import('./src/components/custom/Collapse.vue')['default']
    CollapseItem: typeof import('./src/components/custom/CollapseItem.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Hitokoto: typeof import('./src/components/Hitokoto.vue')['default']
    Links: typeof import('./src/components/Links.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Message: typeof import('./src/components/custom/Message.vue')['default']
    MoreContent: typeof import('./src/components/MoreContent.vue')['default']
    Progress: typeof import('./src/components/custom/Progress.vue')['default']
    Radio: typeof import('./src/components/custom/Radio.vue')['default']
    RadioGroup: typeof import('./src/components/custom/RadioGroup.vue')['default']
    Row: typeof import('./src/components/custom/Row.vue')['default']
    Set: typeof import('./src/components/Set.vue')['default']
    Slider: typeof import('./src/components/custom/Slider.vue')['default']
    SocialLinks: typeof import('./src/components/SocialLinks.vue')['default']
    Switch: typeof import('./src/components/custom/Switch.vue')['default']
    TimeCapsule: typeof import('./src/components/TimeCapsule.vue')['default']
    Tooltip: typeof import('./src/components/custom/Tooltip.vue')['default']
  }
}
